### ISSUE TITLE
Longhaul Nightly Public Dashboard

### ISSUE THREAD

**Issue by tanvigour** [dapr/test-infra#147]
## Describe the proposal

The current longhaul nightly dashboard doesn't have public endpoints exposed to be accessed at a centralized location by public. The way it works currently is, to access the dashboard one has to port forward as follows

`kubectl port-forward svc/grafana 8080:80 -n dapr-monitoring`

then, get the password using the secret 

`kubectl get secret --namespace dapr-monitoring grafana -o jsonpath="{.data.admin-password}" | base64 --decode ; echo`

and then login to the dashboard as admin on localhost:port. There are couple of issues with this method

1. The port forwarding and logging with the secret password is a pain for everyone to be able to simply open the dashboard and monitor the data. 
2. The screenshots etc that are taken when alerts are fired in monitoring channel aren't accessible to everyone just by clicking on  them.

Grafana has recently exposed a feature toggle called "publicDashboards". This is an opt-in feature. According to their documentation to enable this, this needs to be added as a feature toggle to the ini file that grafana installation has, as below

`[feature_toggles]
publicDashboards = true`

This toggle will enable the dashboard to become public. The dashboard needs to be configured after this to be publicly accessible which would then have a public URL that can be shared with everyone.

Since we do our installations using helm we may need to use a different approach to enable this toggle. One way is using helm--set flag. I am currently experimenting locally in my fork with different combinations that may work to enable this feature in grafana helm installation step itself.

Following are some of the limitations to keep in mind going forward with this approach
1. Public dashboards are read-only.
2. Arbitrary queries cannot be run against datasources through public dashboards. Public dashboards can only execute the queries stored on the original dashboard.
3. Template variables are currently not supported, but are planned to be in the future.

**Comment by berndverst** [comment]
Sounds fine to me.

If you want this to work for the entire community we also need to migrate our long haul tests to the non-internal Azure subscription as we cannot expose a public Kubernetes ingress with the internal subscription.

**Comment by artursouza** [comment]
What are the risks for the public dashboard to cause DOS if too many people try to run queries at the same time? Is there a cache layer?

**Comment by johnewart** [comment]
There is a cache feature you can use but I think it may be limited to the enterprise version  https://grafana.com/docs/grafana/latest/enterprise/query-caching/ - not sure if we are able to use the advanced features.

**Comment by johnewart** [comment]
We might be able to get a free enterprise license but if that doesn't work we could probably deploy a cache in front of it -- something like Varnish perhaps?
