### ISSUE TITLE
Container registry unreachable

### ISSUE THREAD

**Issue by elena-kolevska** [dapr/test-infra#225]
The weekly longhaul test deploy is failing because the docker registry seems to be unreachable: https://github.com/dapr/test-infra/actions/runs/9412983983/job/26085560583

Since the registry address is saved in a Github secret, we can't see what's the value, so we can't troubleshoot it. We know it's not a part of the Dapr account on Azure that's used for the longhaul tests.

I suggest we create a new ACR that's going to be used for both weekly and release longhaul tests in the Dapr account, so we have things centralised.
I also think we should save the address in Github as an env variable instead of a secret, for future reference.

**Comment by tmacam** [comment]
We only have 3 ACRs in that subscription and none match the ACR mentioned in the apps images (`daprtests.azurecr.io/pubsub-workflow:dev`, for example)

> I also think we should save the address in Github as an env variable instead of a secret, for future reference.

Agreed.

**Comment by mikeee** [comment]
The ACR `daprtests.azurecr.io` has been recreated by @berndverst should be functional. 

Could you please check whether the apps correctly publish on builds again?

With the registry address - I believe it's in the workflow unless I'm mistaken

https://github.com/dapr/test-infra/blob/0a7d746a302d71cf3eabe7c8a54ea27942813853/.github/workflows/dapr-longhaul-weekly.yml#L30-L31
