### ISSUE TITLE
[Longhaul Test] Stale snapshot monitor

### ISSUE THREAD

**Issue by artursouza** [dapr/test-infra#8]
Even though Hashtag Snapshot Service is working, the last snapshot might be too old. Hashtag Snapshot Service should publish a metric on delay since last successful run. The delay should never be greater than 5 minutes. This metric can be emitted by Hashtag Snapshot Service.

Parents: dapr/dapr#1100 dapr/dapr#1155

**Comment by LMWF** [comment]
Since there is no fault injection I'm going to set the alert to a smaller time. It may require fine tuning over time.
